### ISSUE TITLE
topexpect doesn't put required identifier in string delimiters

### ISSUE THREAD

**Issue by yminsky** [let-def/topexpect#7]
Strings containing `{|` should have a different delimiter on the expect output, but right now it doesn't. Indeed, if one manually adds an identifier after the fact, topexpect will remove it on the next run.

```
[@@@part "4.8"];;
let s = print_endline {x|
OCaml has multiple kinds of quotations,
including ", and {| and |}
|x};;
[%%expect{|
OCaml has multiple kinds of quotations,
including ", and {| and |}

|};
ocaml {|val s : unit = ()|}];;
```

This is from the main.topscript in the records chapter of RWO.

**Comment by let-def** [comment]
Implemented in current master.

**Comment by yminsky** [comment]
I tested this out, and it works great. I think we're ready for another release in opam. Thanks!
